version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: corrupcion_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: corrupcion_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: td8corrupcion
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=es_AR.UTF-8 --lc-ctype=es_AR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - corrupcion_network

volumes:
  postgres_data:

networks:
  corrupcion_network:
    driver: bridge